config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


get '/' => "posts#index"


resources :posts do
  resources :comments
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :author, presence: true
  validates :text, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
has_many :comments

  validates :title, presence: {:message => "Выберите тему поста!!"}
  validates :title, :length => { :maximum => 40, :message => "Слишком длинная тема поста !!"}
  validates :author, presence: true
  validates :content, presence: {:message => "Напишите текст поста!!"}
  validates :content, :length => { :minimum => 123, :message => "Слишком короткий пост!! НУжно больше буков!!"}
  validates :mainpic, presence:  {:message => "Посту нужна обложка!!"}
  validates_format_of :mainpic,  :with => %r{(png|jpg|jpeg)}i, :message => "Неправильный формат файла !!"

mount_uploader :mainpic, PostimageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :email, presence: true
  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?
#before_action :authenticate_user!



protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def new

end

def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)

    redirect_to post_path(@post)

end



def comment_params
    params.require(:comment).permit(:author, :text, :reply)
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  before_action :authenticate_user!



  def index

    @posts_all = Post.all
    
    #create mass for posts
    @posts = []

    # check if there is posts
    if @posts_all.count >0 

          @posts_all.each do |post|
              #check if is it time to publick post
        if post.postdate.to_datetime < DateTime.now.to_datetime
              #add this posts to mass
          @posts << post
              #or if user is post author  add this posts to mass
        elsif current_user.email == post.author

         @posts << post
         

        end

      end  
    end 
    
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new

  end

  def create
    @post = Post.new(post_params)

    #return to form if validation fail
    if  @post.save
        redirect_to @post
      else
        render action: 'new'
      end
  end



 def edit

      @post = Post.find(params[:id]) 

  end


def update

  @post = Post.find(params[:id])

  #check to allowed edition only to authors
  if current_user.email == @post.author
  #return to form if validation fail
     if  @post.update(post_params) 
        redirect_to @post

      else
        render action: 'edit'
      end

    else
      redirect_to @post
    end
end


  def destroy
  end


  def post_params
    params.require(:post).permit(:author, :content, :title, :mainpic, :postdate)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogstar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--devise alerts added-->
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

       <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </head>

  <body>
<div class="container">
  <div class="row">
    <div class="col-lg-2 col-md-2 mx-auto">
    </div>
    <div class="col-lg-8 col-md-8 mx-auto">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Меню</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">

              <%if user_signed_in?%>
              <a class="nav-item nav-link" href=<%=posts_path%>>Главная <span class="sr-only">(current)</span></a>
              <a class="nav-item nav-link"><%=current_user.email%></a>
                <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></p2><hr/><br/>
                <%end%>
             <!-- <a class="nav-item nav-link" href="#">Pricing</a>
              <a class="nav-item nav-link disabled" href="#">Disabled</a>-->
            </div>
          </div>
        </nav>
    </div>
    <div class="col-lg-2 col-md-2 mx-auto">
    </div>

  </div>
</div>
<br/><br/><hr/>

      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-8 mx-auto">
            <%= yield %>
            <br/><br/><br/><br/><br/><hr/> 
            <p2> Контакты@Почта_и_всякое_такое</p2>


          </div>
        </div>
      </div>

  </body>

<script>

$(function () {
  $('[data-toggle="popover"]').popover()




   CKEDITOR.editorConfig = function( config )
{
   // misc options
   config.height = '500px';
};
})
</script>

</html>

app/views/posts/edit.html.erb
<%= form_for :post,  url: post_path(@post), method: :put do |f| %> 

<h1> <%= f.hidden_field  :author, value: current_user.email %> </h1>

	<t2> <%= f.label :Тема_поста %> </t2><br/>
	<p1> <%= f.text_field  :title, size: "50x1", value: @post.title  %> </p1><br/>

	<t2><%= f.label :Текст_поста %> </t2><br/>
	<textarea  name="post[content]"> <%= @post.content%>
	</textarea>
	<br/>


	<t2><%= f.label :Обложка_поста %></t2>
    <p1><%= f.file_field :mainpic, value: @post.mainpic  %></p1><br/>


	<t2><%= f.label :Выбрать_дату_публикации_поста %></t2>
    <p1><%= f.datetime_select :postdate.to_s, value: DateTime.now %></p1><br/>


	<button class="btn btn-primary" type="submit">Отправить изменения</button>
 <%end%>



<!--augmented text editor -->
<script>
      CKEDITOR.replace( 'post[content]');
</script>

app/views/posts/index.html.erb
<!--check if user signed-->
<%if user_signed_in?%>

    <a class="btn btn-outline-success pull-right" href=<%=new_post_url%>> Написать новый пост </a><br/><br/><hr/>      
          
        
<%end%>

<!--check if there are posts-->
<%if @posts != nil%>
<%@posts.each do |post|%>


<a href = <%=post_url(post)%>>
<h4 class="text-left">
  <%=post.title%></h4><br/>

<img  class="img-fluid"  style="height: 250px;" src=<%=post.mainpic%>><br/>

<h4 class="text-left">
  <%=post.content.html_safe%></h4><br/>


<button type="button" class="btn btn-outline-primary pull-right"> читать далее...</button></a><br/><br/><hr/>


<%end%>
<%end%>

app/views/posts/new.html.erb
<!--new post creation -->
<%= form_for :post,  url: posts_path do |f| %> 

<!--errors display -->
<% if @post.errors.any? %>
            <div id="errorExplanation">
            	 
                <ul>
                    <% @post.errors.messages.each do |msg| %>
				<div class="alert alert-danger">
                    <li><%= msg[1][0]%></li>
               	</div>
                    <% end %>
                  </ul>
             
            </div>
  <% end %>

<t4> Написать новый пост: </t4>
	<h1> <%= f.hidden_field  :author, value: current_user.email %> </h1>

	<t2> <%= f.label :Тема_поста %> </t2><br/>
	<p1> <%= f.text_field  :title, size: "50x1", value: @post.title  %> </p1><br/>

	<t2><%= f.label :Текст_поста %> </t2><br/>
	<textarea  name="post[content]"> <%= @post.content%>
	</textarea>
	<br/>


	<t2><%= f.label :Обложка_поста %></t2>
    <p1><%= f.file_field :mainpic %></p1><br/>


	<t2><%= f.label :Выбрать_дату_публикации_поста %></t2>
    <p1><%= f.datetime_select :postdate.to_s, value: DateTime.now %></p1><br/>


	<button class="btn btn-primary" type="submit">Создать пост</button>
 <%end%>

<!--augmented text editor -->
<script>
      CKEDITOR.replace( 'post[content]');
</script>

app/views/posts/show.html.erb
<h4 class="text-left">
  <%=@post.title%></h4><br/>
<img  class="img-fluid"  style="height: 250px;" src=<%=@post.mainpic%>><br/>
<h4 class="text-left">
  <%=@post.content.html_safe%></h4><br/>
   
 <br/><br/><hr/>

<!--check if user is author, then edition showed-->
<%if current_user.email == @post.author%>
  <%= link_to "Редактировать пост", edit_post_path(@post)  %><br/><hr/>
<%end%>

<!--comments add form-->
 <%= form_for ([@post, @post.comments.build]) do |f| %>
 <%= f.hidden_field  :author,  value:  current_user.email %>

  <p2> Комментарии: </p2><br/>
    <button type="button" class="btn btn-outline-primary"><%=current_user.email%></button><br/>

    <!--reply to input-->
      <input readonly type="text" class="alert alert-light" name = "comment[reply]" id = "reply"/><br/>


      <t2> <%= f.text_field :text%></t2>

      <button type="submit" class="btn btn-outline-primary">Отправить</button></a><br/><br/><hr/>



 <%end%>             

<!--comments-->

<% @post.comments.reverse_each do |comment| %>
    <!--check if there is a comments -->
      <%if comment.text !=nil %>

      <!--different comments show for comments authors-->
        <%if current_user.email == comment.author%>

            <button type="button" class="float-right btn btn-outline-dark">Комментарий №<%=comment.id%></button><br/><br/>

            <button type="button" class="float-right btn btn-success"><%=comment.author%></button><br/><br/>
              <!--check if there is a reply-->
              <%if comment.reply.to_i>0%>

              <button type="button" class="float-right btn btn-secondary" data-container="body" data-toggle="popover" data-placement="left" data-content="<%=Comment.find(comment.reply.to_i).text%>">
              Ответил на комментарий № <%=comment.reply%>
            </button><br/><br/>


              <%end%>

              <button type="button" class="float-right btn btn-outline-dark"><%=comment.text%></button><br/><br/><hr/>

        <%else%>

                <button type="button" class="float-left btn btn-outline-dark">Комментарий №<%=comment.id%></button><br/><br/>

                <button   type="button" class="float-left btn btn-primary"><%=comment.author%></button><br/><br/>

                 <button class="type btn btn-dark" type="button" name="submit" id=<%=comment.id%>>ОТВЕТИТЬ</button>

                <%if comment.reply.to_i>0%>
               
                <button type="button" class="float-left btn btn-secondary" data-container="body" data-toggle="popover" data-placement="left" data-content="<%=Comment.find(comment.reply.to_i).text%>">
                Ответил на комментарий № <%=comment.reply%>
              </button><br/><br/>
                <%end%>
                <button  type="button" class="float-left btn btn-outline-dark"><%=comment.text%></button><br/><br/><hr/>

           
            <%end%>
        <%end%>
<%end%>


<!--script to add comment number to input form-->
<script>
$(function(){
    $(".type").on("click", function(){
        var id = $(this).attr("id");
        $("#reply").val(id);
    });
});
</script>